ingest_data_from_gdrive:
  source_URL: https://drive.google.com/file/d/1_xaRB6d2K_9-1dUmdU0GjtaqPO7uQnTM/view
  local_data_dir: datasets
  local_data_file: datasets/SPOTIFY_REVIEWS.csv
  force_ingest: False

pincone_upsert_docs:
  local_data_file: datasets/SPOTIFY_REVIEWS.csv
  load_data_file: datasets/SPOTIFY_REVIEWS_LOAD.csv
  data_length: 50
  source_column: review_id
  metadata_column:
  - review_rating
  - review_likes
  - author_app_version
  - review_timestamp
  - pseudo_author_id
  - author_name
  - review_id
  namespace: ns-0
  embedding_model: text-embedding-3-large
  chunk_size: 800
  chunk_overlap: 0
  document_dimension: 1536
  id_prefix: id
  force_upsert: False

qna:
  embedding_model: text-embedding-3-large
  document_dimension: 1536
  namespace: ns-0
  llm: gpt-3.5-turbo-instruct
  temperature: 0

memory:
  llm: gpt-3.5-turbo-instruct